### ISSUE TITLE
`Regression*_test:bvals` failing on develop

### ISSUE THREAD

**Issue by lroberts36** [parthenon-hpc-lab/parthenon#785]
```bash
50: Test command: /vast/home/lfroberts/.conda/envs/parthenon/bin/python3.10 "/vast/home/lfroberts/parthenon/tst/regression/run_test.py" "--driver" "/vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example" "--driver_input" "/vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals" "--num_steps" "3" "--test_dir" "/vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals" "--output_dir" "/vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/tst/regression/outputs/bvals" "--kokkos_args="
50: Test timeout computed to be: 1500
50: 
50: 
50: test_dir=['/vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals']
50: output_dir='/vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/tst/regression/outputs/bvals'
50: driver=['/vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example']
50: driver_input=['/vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals']
50: kokkos_args=['']
50: num_steps=3
50: mpirun=''
50: mpirun_ranks_flag=None
50: mpirun_ranks_num=1
50: mpirun_opts=[]
50: coverage=False
50: analyze=False
50: sparse_disabled=False
50: *****************************************************************
50: Beginning Python regression testing script
50: *****************************************************************
50: 
50: Initializing Test Case
50: Using:
50: driver at:       /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example
50: driver input at: /vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals
50: test folder:     /vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals
50: output sent to:  /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/tst/regression/outputs/bvals
50: 
50: Make output folder in test if does not exist
50: *****************************************************************
50: Preparing Test Case Step 1
50: *****************************************************************
50: 
50: *****************************************************************
50: Running Driver
50: *****************************************************************
50: 
50: Command to execute driver
50: /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example -i /vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals parthenon/mesh/ix1_bc=reflecting parthenon/mesh/ox1_bc=reflecting parthenon/mesh/ix2_bc=reflecting parthenon/mesh/ox2_bc=reflecting parthenon/mesh/ix3_bc=reflecting parthenon/mesh/ox3_bc=reflecting parthenon/output0/id=reflecting
50: *****************************************************************
50: Preparing Test Case Step 2
50: *****************************************************************
50: 
50: *****************************************************************
50: Running Driver
50: *****************************************************************
50: 
50: Command to execute driver
50: /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example -i /vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals parthenon/mesh/ix1_bc=periodic parthenon/mesh/ox1_bc=periodic parthenon/mesh/ix2_bc=periodic parthenon/mesh/ox2_bc=periodic parthenon/mesh/ix3_bc=periodic parthenon/mesh/ox3_bc=periodic parthenon/output0/id=periodic
50: *****************************************************************
50: Preparing Test Case Step 3
50: *****************************************************************
50: 
50: *****************************************************************
50: Running Driver
50: *****************************************************************
50: 
50: Command to execute driver
50: /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/example/advection/advection-example -i /vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/parthinput.advection_bvals parthenon/mesh/ix1_bc=outflow parthenon/mesh/ox1_bc=outflow parthenon/mesh/ix2_bc=outflow parthenon/mesh/ox2_bc=outflow parthenon/mesh/ix3_bc=outflow parthenon/mesh/ox3_bc=outflow parthenon/output0/id=outflow
50: Running with coverage
50: False
50: *****************************************************************
50: Analysing Driver Output
50: *****************************************************************
50: 
50: 
50:         *** ERROR: Unable to open advection.reflecting.00004.phdf as phdf file
50:         
50: FileNotFoundError(2, 'No such file or directory')
50: Double reflection test failed: output start != end 
50: Tolerance = 1e-12
50: 
50:         *** ERROR: Unable to open advection.periodic.00004.phdf as phdf file
50:         
50: FileNotFoundError(2, 'No such file or directory')
50: Fully periodic test failed: output start != end 
50: Tolerance = 1e-12
50: Traceback (most recent call last):
50:   File "/vast/home/lfroberts/parthenon/scripts/python/packages/parthenon_tools/parthenon_tools/phdf.py", line 87, in __init__
50:     f = h.File(filename, "r")
50:   File "/vast/home/lfroberts/.conda/envs/parthenon/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
50:     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
50:   File "/vast/home/lfroberts/.conda/envs/parthenon/lib/python3.10/site-packages/h5py/_hl/files.py", line 220, in make_fid
50:     fid = h5f.open(name, flags, fapl=fapl)
50:   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
50:   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
50:   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
50: FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'advection.outflow.00004.phdf', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
50: 
50: During handling of the above exception, another exception occurred:
50: 
50: Traceback (most recent call last):
50:   File "/vast/home/lfroberts/parthenon/tst/regression/run_test.py", line 204, in <module>
50:     main(**vars(args))
50:   File "/vast/home/lfroberts/parthenon/tst/regression/run_test.py", line 88, in main
50:     test_result = test_manager.Analyse()
50:   File "/vast/home/lfroberts/parthenon/tst/regression/utils/test_case.py", line 278, in Analyse
50:     test_pass = self.test_case.Analyse(self.parameters)
50:   File "/vast/home/lfroberts/parthenon/tst/regression/test_suites/bvals/../../test_suites/bvals/bvals.py", line 133, in Analyse
50:     outflow_data_final = phdf.phdf("advection.outflow.00004.phdf")
50:   File "/vast/home/lfroberts/parthenon/scripts/python/packages/parthenon_tools/parthenon_tools/phdf.py", line 89, in __init__
50:     raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filename)
50: FileNotFoundError: [Errno 2] No such file or directory: 'advection.outflow.00004.phdf'
1/1 Test #50: regression_test:bvals ............***Failed    1.74 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
regression    =   1.74 sec*proc (1 test)
serial        =   1.74 sec*proc (1 test)

Total Test time (real) =   1.77 sec

The following tests FAILED:
         50 - regression_test:bvals (Failed)
Errors while running CTest
Output from these tests are in: /vast/home/lfroberts/parthenon/build-nvidia-devkit-cuda-2022-06-23/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

This is the failure output I get on a Darwin `nv-devkit` node. It appears that the github CI is running into the same issue.

**Comment by lroberts36** [comment]
Test passes in `d839a8d8` but fails in the next commit `13f6720` which is the first commit of PR #784. @bprather was this passing on that branch originally? 

It looks like the github CI is never running the full test suite on PRs but it is running the full test suite on develop. Is there a reason we are not at least running the full suite of serial tests on the PR CI @pgrete?

**Comment by c-prather** [comment]
Wait the first commit?  That should fail, I messed up the logic.

If it fails on the second/last commit of that PR then I'm worried, changing that condition shouldn't affect output in any test context, just sometimes remove the last numbered dump when one is produced on or nearly every step.

Is there a docs page somewhere on the tests?  I've never run them manually, so it'll take me a bit to get up & running trying this for myself on Darwin, I think

**Comment by lroberts36** [comment]
It also fails on `b58cdd31c1` (the current HEAD of develop). `13f6720` is the first commit it fails on, but I did not test the intervening commits. 

I think if you compile with the tests enabled (which is default), you should just be able to run `ctest` in your build directory and it will run all of the tests. To just run the failing test you can run `$ ctest -V -R regression_test:bvals`.

**Comment by c-prather** [comment]
Thanks, that should be all I need. I'll take a look now.

EDIT: this definitely appears to be the patch working as intended: the tests expect a last numbered output even when outputs are made very close together or every step. Is there a reason not to switch to the 'final' files (and then update the tests to use the optional backward-compatible behavior when #752 gets addressed)?

**Comment by pgrete** [comment]
> It looks like the github CI is never running the full test suite on PRs but it is running the full test suite on develop. Is there a reason we are not at least running the full suite of serial tests on the PR CI @pgrete?

Yes, as mentioned during the call yesterday, we only run the short tests on every push in order to reduce the load (and thus wait times) on the CI machine.
Also, as discussed yesterday, we now enforce a successful (but manually triggered) extened cI run for each PR prior to merging.
